### ISSUE TITLE
How to generate mandat file by ftp /sftp

### ISSUE THREAD

**Issue by benhbenny** [SlimPay/hapiclient-php#3]
Hi, need your help again.
We need to get by sftp the generate mandat file  but   all genrate file have a specifique name  like mandaat-xxxxxxxxx.pdf  with xxxx is a numeric number.
is there somes possibility to add the rum in generate file name?
or any possibility to get the file by RUM  value?

any help or suggestion will be great

best regards

**Comment by YoussefBO** [comment]
Hi!

Please use this repository for issues regarding the HAPI Client itself only. For questions/requests regarding the SlimPay product, please contact our support:
- through the ticketing system accessible from your Back Office
- or by sending an e-mail to ticketing@slimpay.com

Thank you for your comprehension.

**Comment by benhbenny** [comment]
Sorry for that mistake and thanks for you reply
