### ISSUE TITLE
Upgrade Guzzle

### ISSUE THREAD

**Issue by mremi** [SlimPay/hapiclient-php#4]
Hi,

Is there a work in progress to support the latest Guzzle version?

Thanks

**Comment by YoussefBO** [comment]
Hi,
Not at the moment but definitely something we want to do.
Still wondering if we should keep the support for both in two different branches as Guzzle did or should we just drop 5.* support and upgrade to 6.*.

What's your opinion on this?

**Comment by sylvainvuidart** [comment]
Hi,

Same problem for me. Guzzlehttp version conflict (5.3.1, 6.2.1) with composer due to another library requirement.
Will you fix that or should I fork your lib ?

**Comment by YoussefBO** [comment]
Hi,

We can't "fix" it per say but we will open a new branch in this same repository and make this new branch Guzzle 6.* compatible.

Sadly I can't give any approximate ETA.
If you happen to be in a hurry, you can indeed fork the lib.

**Comment by YoussefBO** [comment]
Hi all,

I'm glad to announce this repository is now compatible with Guzzle 6.* starting from v1.0.2: cea4f7e4604d3aa58f6dce2a2d71d202bc6fa5c5

We chose to keep compatibility for both Guzzle 5.3 and 6.* in the same branch.
Feel free to open an issue if you encounter any unexpected behavior. Thanks.
