### ISSUE TITLE
No PHP examples on HAPI Browser page

### ISSUE THREAD

**Issue by hakikihacioglu** [SlimPay/hapiclient-php#5]
Do I miss something? I don't find any examples of the api for php on https://dev.slimpay.com/hapi/browser

**Comment by YoussefBO** [comment]
Hi hakikihacioglu,

1. Choose a relation (ex. create-orders)
2. At the top of the right side, click on HTTP/1.1
3. Select HAPI Client PHP instead.

The code on the right will now be formatted for this library giving you a fill example including:
- inclusion of the autoload
- instantiation of the client with the credentials to the API
- preparation of the request
- sending the request

Do not hesitate if you need more.

PS: more documentation will follow soon in the README of this repository on how to use it.
