### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by GH974** [SlimPay/hapiclient-php#7]
Hi, I use the sample code on your site _**"https://dev.slimpay.com/hapi/guide/30-min-integration/easy-step-by-step"**_. I have got an access on your back office and I have one Appid and Appsecret. I have error "403 Forbidden". Have you idea? Thanks

**Comment by SlimPay** [comment]
Hello,

Can you please provide ypur creditor reference (provided to you with you
test account details)?

Can you also confirm you also replaced the following values with your own
on the part of code to copy?
-Creditor reference
-app_id
-App_secret

A 403 error generally means you are using wrong credentials.

Regards

Maxime

**Comment by GH974** [comment]
I have copy/past, my credentials in the backoffice, in the code sample. I have a question, the "app_id" and the "Creditor reference" are they identical?

**Comment by SlimPay** [comment]
They are not always the same. What are yours?
Regards

**Comment by GH974** [comment]
I received the App Name and App Secret in my email, I don't received Creditor Reference. I find where creditor Reference?

**Comment by SlimPay** [comment]
Can you please provide the app_id to me ?

Creditor_reference is provided along with the app_id.

Regards

Maxime
ᐧ

Maxime Leconte
Head of Onboarding
Phone: +33 1 77 63 55 60
Skype: maxime.leconte_slimpay

12 rue Godot de Mauroy, 75009 Paris - FRANCE
SlimPay.com <http://www.slimpay.com/>  |  Twitter
<https://twitter.com/SlimPay>  |  Facebook
<https://www.facebook.com/SlimPay-105254479543044/>  |  Linkedin
<https://www.linkedin.com/company/slimpay>

<http://www.slimpay.com/>

**Comment by GH974** [comment]
app_id: protectassos

**Comment by SlimPay** [comment]
Thank you.

This app_id does not exist in our system. But I guess this is related to
Groupe BHBV. Can you confirm ?

In this case you will need to provide different credentials.

To go further with the subject, can you please answer this email to
onboarding@slimpay.com ?

Regards,
ᐧ

Maxime Leconte
Head of Onboarding
Phone: +33 1 77 63 55 60
Skype: maxime.leconte_slimpay

12 rue Godot de Mauroy, 75009 Paris - FRANCE
SlimPay.com <http://www.slimpay.com/>  |  Twitter
<https://twitter.com/SlimPay>  |  Facebook
<https://www.facebook.com/SlimPay-105254479543044/>  |  Linkedin
<https://www.linkedin.com/company/slimpay>

<http://www.slimpay.com/>

**Comment by GH974** [comment]
Yes I confirm. I prefere switch to email address, Can you remove this ticket?

**Comment by SlimPay** [comment]
Yes, sure.

Just send an email to onboarding@slimpay.com.

This will send an email to our team so that any of us can follow up your
issue and quickly answer to you.

Regards,

Maxime
ᐧ

Maxime Leconte
Head of Onboarding
Phone: +33 1 77 63 55 60
Skype: maxime.leconte_slimpay

12 rue Godot de Mauroy, 75009 Paris - FRANCE
SlimPay.com <http://www.slimpay.com/>  |  Twitter
<https://twitter.com/SlimPay>  |  Facebook
<https://www.facebook.com/SlimPay-105254479543044/>  |  Linkedin
<https://www.linkedin.com/company/slimpay>

<http://www.slimpay.com/>

**Comment by GH974** [comment]
Ok thanks
